In [4]:
import pandas as pd
import os


pd.set_option("display.max_columns", None)

In [5]:
df = pd.read_excel('rech.xlsx')
df.columns

Index(['Unnamed: 0', ' Tipo de justificativa', 'Colaborador', 'Empresa',
       'Filial', 'CPF', 'Data Inicial do afastamento',
       'Quantidade de Dias de Afastamento',
       'Estou ciente que só devo retornar ao trabalho ao fim dos dias de atestado.',
       'Observações', 'Justificativa', 'Justificativa Validada',
       'data_abertura', 'Cadastro', 'Ciente do Gestor', 'E-mail Pessoal',
       'Telefone Pessoal', 'Formulário', 'Certidão de Nascimento',
       'Grau de Parentesco', 'Data do Abono', 'Autorização do Gestor',
       'Motivo de Justificativa - Recusada', ' Empresa'],
      dtype='object')

In [6]:
df

,Unnamed: 0,Tipo de justificativa,Colaborador,Empresa,Filial,CPF,Data Inicial do afastamento,Quantidade de Dias de Afastamento,Estou ciente que só devo retornar ao trabalho ao fim dos dias de atestado.,Observações,Justificativa,Justificativa Validada,data_abertura,Cadastro,Ciente do Gestor,E-mail Pessoal,Telefone Pessoal,Formulário,Certidão de Nascimento,Grau de Parentesco,Data do Abono,Autorização do Gestor,Motivo de Justificativa - Recusada,Empresa
0,0,Atestado Odontologico,FELIX DE CASTRO GUIMARAES JUNIOR,TRACTOR PARTS MATRIZ,TRACTOR ORGANIZACAO CENTRAL,051.545.661-65,25/07/2025,2,true,Bom dia,atestado.pdf,Sim.,04/08/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Declaração de comparecimento – Médico,LEANDRO DONDONI,TRACTOR PARTS MATRIZ,TRACTOR SORRISO,030.943.341-05,22/07/2025,MEIO DIA,true,NO DIA 22/07 TIVE QUE ME AUSENTAR DA LOJA PAR...,ATESTADO LEANDRO.pdf.,NaN,04/08/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Atestado Médico,VITOR HUGO LIMA PEREIRA,TELMAC,RIBEIRAO PRETO,240.501.838-11,16/07/2025,1,false,segue atestado,WhatsApp Image 2025-07-23 at 19.11.37.jpeg.,NaN,04/08/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Atestado Médico,DAIANA ASPIR DA SILVA,RECH AGRICOLA,SEDE ADM ITAJAI,018.710.250-36,23/07/2025,2,true,Dia 24 eu trabalhei,WhatsApp Image 2025-07-28 at 10.19.00.jpeg.,NaN,04/08/2025,1771,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Atestado Médico,DAIANA ASPIR DA SILVA,RECH AGRICOLA,SEDE ADM ITAJAI,018.710.250-36,01/08/2025,1,true,NaN,WhatsApp Image 2025-08-01 at 12.54.36.jpeg,Sim.,04/08/2025,1771,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,217,Atestado Médico,THIAGO VASCONCELOS DA SILVA,RECH AGRICOLA,NAVEGANTES,098.422.109-36,07/08/2025,2,true,NaN,WhatsApp Image 2025-08-07 at 10.27.21.jpeg,Sim.,13/08/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,218,Declaração de comparecimento – Médico,BRUNA LUIZA DA SILVA BRANDENBURG,RECH AGRICOLA,HORIZONTINA,042.115.110-25,11/08/2025,0,false,FUI CONSULTAR DE DERMATOLOGIA. EM ANEXO COMPR...,DERMATOLOGISTA 11.08.jpg,Sim.,14/08/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,219,Atestado Médico,FILIPE SILVA DE SOUSA VIEIRA,TRACTOR PARTS MATRIZ,7,071.823.951-26,18/08/2025,3,true,NaN,Scanner21082025.pdf,Sim.,21/08/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,220,Atestado Médico,WALISON APARECIDO MEDEIROS,TELMAC,RIBEIRAO PRETO,456.708.438-19,20/08/2025,1,true,NaN,IMG_20250821_074756 (1).jpg,Sim.,21/08/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,221,Atestado Médico,MOISES DA SILVA SOUZA,RECH AGRICOLA,GOIANIA LA,702.821.781-71,20/08/2025,1 dia,true,NaN,d273606a-9064-4d6b-949f-d0f46dabff2a.jpg,Sim.,22/08/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df = pd.read_excel('./data/rech/ATESTADOS_RECH_08_09_2025.xlsx')
df = df.loc[df['cpf'].notna()]
# df.loc[df['cpf'].notna()]
df.shape

(45, 19)

In [14]:
df = pd.read_json('./data/greif/temp/chamados_suporte_enduser_retorno_new.json')

df = df.join(pd.json_normalize(df['Status / Prazos']))
df.drop(columns='Status / Prazos', inplace=True)

df = df.join(pd.json_normalize(df['Protocolo - Funcionário - Matrícula ']))
df.drop(columns='Protocolo - Funcionário - Matrícula ', inplace=True)

df = df.join(pd.json_normalize(df['Assunto - Tópicos - Descrição']))
df.drop(columns='Assunto - Tópicos - Descrição', inplace=True)

df = df.join(pd.json_normalize(df['Redirecionamentos']))
df.drop(columns='Redirecionamentos', inplace=True)

df['Prazo'] = df['Prazo'].str.strip().str.split(' ').str[0].astype('Int64')

df['Data Abertura'] = pd.to_datetime(df['Data Abertura']).dt.floor('D')
df['Data Encerramento'] = df['Data Abertura'] + pd.to_timedelta(df['Prazo'], unit='D')

df.drop(columns=df.columns[0], inplace=True)
df

df.to_excel('ATESTADOS_GREIF_NOVO.xlsx')
df

,Empresa,Status,Prazo,Número Chamado,Funcionário,Matrícula do Funcionário,Data Abertura,Data Encerramento,Responsável,Assunto,Tópicos,Descricao,Data Redirecionamento,Responsável Redirecionado:
0,GREIF ARATU,Pendente,5,20332,JACKSON GOES DA SILVA,303227,2025-09-01,2025-09-06,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,None,Expert
1,Greif RJ,Pendente,5,20331,ALEXANDRE PEREIRA GONZALEZ,207791,2025-09-01,2025-09-06,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,None,Expert
2,GREIF MANAUS,Pendente,5,20329,DEUGECIR ALVES FERNANDES,94342,2025-09-01,2025-09-06,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,None,Expert
3,GREIF LONDRINA,Pendente,5,20317,BRUNA APARECIDA DA SILVA,1400437,2025-08-29,2025-09-03,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,None,Expert
4,GREIF ESTEIO,Pendente,5,20315,MARCIO ROGERIO TAVARES,602493,2025-08-29,2025-09-03,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,None,Expert
5,GREIF ESTEIO,Pendente,5,20314,MARCIO ROGERIO TAVARES,602493,2025-08-29,2025-09-03,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,None,Expert
6,Greif RJ,Pendente,5,20308,WILLIAN BELO AVILA MARQUES,208014,2025-08-29,2025-09-03,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,None,Expert
7,Greif SP,Pendente,5,20307,RICARDO ALEXANDRE DOS SANTOS,141195,2025-08-29,2025-09-03,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,None,Expert

In [54]:
df = pd.read_excel('./data/rech/ATESTADOS_RECH_NOVO_NAO_TRATADO.xlsx')
# df.info()

# hasDigit = lambda string: df['Quantidade de Dias de Afastamento'].str.strip().str.split(' ').str[0].str.isdigit

df['Quantidade de Dias de Afastamento'] = pd.to_numeric(
    df['Quantidade de Dias de Afastamento'].str.strip().str.split(' ').str[0], 
    errors='coerce'
)
# df['Quantidade de Dias de Afastamento'] = df['Quantidade de Dias de Afastamento'].str.strip().str.split(' ').str[0].astype('Int64')\
#                                             if hasDigit(df['Quantidade de Dias de Afastamento'].str.strip().str.split(' ').str[0])\
#                                             else df['Quantidade de Dias de Afastamento']

df['Data Inicial do afastamento'] = pd.to_datetime(df['Data Inicial do afastamento'], errors='coerce', dayfirst=True).dt.floor('D')

# Calcular data fim afastamento
df['data fim afastamento'] = df.apply(
    lambda row: row['Data Inicial do afastamento'] + pd.to_timedelta(row['Quantidade de Dias de Afastamento'], unit='D')
    if pd.notna(row['Data Inicial do afastamento']) and pd.notna(row['Quantidade de Dias de Afastamento'])
    else pd.NaT,
    axis=1
)

df = df[df['Data Inicial do afastamento'] > pd.to_datetime('18/08/2025', dayfirst=True)]


# Normalizar hora e manter apenas a data
df['data fim afastamento'] = df['data fim afastamento'].dt.normalize()

# Se quiser mostrar no formato Y-m-d como string
df['data fim afastamento'] = df['data fim afastamento'].dt.strftime('%Y-%m-%d')
df['Data Inicial do afastamento'] = df['Data Inicial do afastamento'].dt.strftime('%Y-%m-%d')

# df = df[df['Data Inicial do afastamento'] > pd.to_datetime('19/09/2025', dayfirst=True)]
# df.drop(columns='data fim afastamento', inplace=True)



df.to_excel('teste.xlsx', index=False)
df

,Tipo de justificativa,Colaborador,Empresa,Filial,CPF,Data Inicial do afastamento,Quantidade de Dias de Afastamento,Estou ciente que só devo retornar ao trabalho ao fim dos dias de atestado.,Observações,Justificativa,...,E-mail Pessoal,Telefone Pessoal,Formulário,Certidão de Nascimento,Ciente do Gestor,Grau de Parentesco,Data do Abono,Autorização do Gestor,Empresa,data fim afastamento
102,Atestado Médico,ALIANA CARLA TODESCHINI GUIMARAES,RECH AGRICOLA,HORIZONTINA,925.405.890-49,2025-08-19,1.0,false,Bom dia!\nEstive ausente do trabalho por um p...,Atestado 19.08.2025.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-20
106,Atestado Médico,LUIZ EDUARDO CASSITA,RECH AGRICOLA,LUIS EDUARDO MAGALHAES LV,052.703.935-73,2025-08-20,1.0,true,Bom dia! \nGostaria de informar meu atestado ...,340f39c9-9a54-4cd8-9740-0679f682a98f.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-21
107,Atestado Médico,TALIA MILENA GOMES DA SILVA,TRACTOR PARTS MATRIZ,TRACTOR SINOP,030.192.582-86,2025-08-19,1.0,true,Atestado do período matutino,CCF20082025_0005.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-20
109,Atestado Médico,THIAGO VASCONCELOS DA SILVA,RECH AGRICOLA,NAVEGANTES LA,098.422.109-36,2025-08-20,2.0,true,NaN,WhatsApp Image 2025-08-20 at 10.08.03.jpeg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-22
110,Atestado Médico,GABRIELA CARDOSO DE SOUZA,RECH AGRICOLA,NAVEGANTES LA,530.635.058-54,2025-08-21,NaN,true,favor considerar o deslocamento e se atentar ...,e0780ccc-77f2-4694-a433-4f1143a9ce19.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,Atestado Médico,JOAO VITOR AUGUSTO ASSUNCAO,TRACTOR PARTS MATRIZ,TRACTOR VARZEA GRANDE,066.877.751-62,2025-08-21,NaN,true,estava ao medico,Arquivo_073088.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,Atestado Médico,LUIZ EDUARDO CASSITA,RECH AGRICOLA,LUIS EDUARDO MAGALHAES LV,052.703.935-73,2025-08-22,1.0,true,Bom dia! \nGostaria de informar meu atestado ...,atestado.png,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-23
114,Atestado Médico,MARIELLI RODRIGUES DE SOUZA,TRACTOR PARTS MATRIZ,luis ed,708.467.221-43,2025-08-22,0.0,true,Bom dia,atestado-marielli-22-08.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-22
115,Atestado Médico,MICHELI LINASSI,RECH AGRICOLA,PRIMAVERA DO LESTE LV,012.048.491-96,2025-08-22,1.0,true,NaN,IMG_20250822_124929.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-23
116,Atestado Médico,KELLE MAGDA DOS SANTOS CARNEIRO RIBEIRO,Rech,55,050.094.702-33,2025-08-19,1.0,true,NaN,Consulta obstetra 19-08.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-20
117,Atestado Médico,INGRID OLIVEIRA DA SILVA,TELMAC,RIBEIRAO PRETO,414.281.898-82,2025-08-25,1.0,false,feito exame e atesto do dia 25/08,Imagem do WhatsApp de 2025-08-26 à(s) 11.04.5...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-26
119,Atestado Médico,TAINARA DANIELI SARTORI,RECH AGRICOLA,HORIZONTINA,035.336.000-76,2025-08-26,1.0,true,NaN,2608.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-27
120,Atestado Médico,MARCIANE DA ROSA,RECH AGRICOLA,HORIZONTINA,985.394.770-68,2025-08-22,1.0,true,19 PRA IR NA CONSULTA MÉDICA.,WhatsApp Image 2025-08-27 at 08.16.17.jpeg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-23
121,Atestado Médico,JOAO FRANCISCO DOS REIS,TRACTOR PARTS MATRIZ,TRACTOR TANGARA DA SERRA,181.494.778-70,2025-08-25,1.0,true,ANEXO ATESTADO CONSULTA E PROCEDIMENTO OFTALM...,CamScanner 25-08-2025 09.52.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-26
122,Declaração de comparecimento – Médico,ELENA RIBEIRO DE MELO,TRACTOR PARTS MATRIZ,TRACTOR SORRISO,062.363.981-51,2025-08-28,NaN,true,Bom dia,DECLARAÇÃO E COMPARECIMENTO ELENA 28082025.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Atestado Médico,MADISON ANJOS DA SILVA,RECH AGRICOLA,SANTAREM LA,898.726.732-68,2025-08-28,1.0,false,precisou ir ao médico na parte da tarde,CCF_000057.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-29
124,Atestado Médico,JOAO VITOR AUGUSTO DE ASSUNCAO,TRACTOR PARTS MATRIZ,TRACTOR VARZEA GRANDE,NaN,2025-08-27,1.0,true,ESTAVO AO MEDICO.,Arquivo_073898.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-28
125,Atestado Médico,TANIA DOS SANTOS ATAIDE DE CASTRO LEAO,RECH AGRICOLA,VARZEA GRANDE LA,366.872.781-34,2025-08-28,NaN,true,Boa tarde!\n\nSegue anexado atestado médico,ATESTADO 28-08-25.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,Atestado Médico,ANTHONY SILVA MOURAO,TRACTOR PARTS MATRIZ,TRACTOR VARZEA GRANDE,050.285.501-07,2025-08-28,2.0,true,NaN,Arquivo_041170.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-30
127,Atestado Médico,EDUARDO HENRIQUE GERALDO ALVES,TRACTOR PARTS MATRIZ,NOVA MUTUM LV,078.198.409-27,2025-08-29,2.0,false,O colaborar sofreu um pequeno acidente no tr...,atestado Eduardo Henrique Geraldo Alves.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-31
128,Atestado Médico,KATLEN RAFAELA FORNALSKI SAPIESZYNSKI,RECH AGRICOLA,HORIZONTINA,031.808.720-04,2025-08-28,3.0,true,Boa tarde!\nSolicito lançamento do atestado.\...,Atestado Kathen.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-31
129,Atestado Médico,EDIMAR TRINDADE DE SOUZA,TRACTOR PARTS MATRIZ,TRACTOR LUIS EDUARDO MAGALHAES,020.753.575-28,2025-08-28,1.0,true,Atestado referente a ausência,Edmar-29-08.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-29
130,Atestado Médico,LUIZ GUSTAVO RODOLPHO,RECH AGRICOLA,PRIMAVERA DO LESTE LV,068.384.841-02,2025-08-27,1.0,true,NaN,Adobe Scan 30 de ago. de 2025 (2).pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-28
131,Atestado Médico,LUIZ GUSTAVO RODOLPHO,RECH AGRICOLA,PRIMAVERA DO LESTE LV,068.384.841-02,2025-08-28,1.0,true,NaN,Adobe Scan 30 de ago. de 2025.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-29
178,Atestado Médico,WALISON APARECIDO MEDEIROS,TELMAC,RIBEIRAO PRETO,456.708.438-19,2025-08-20,1.0,true,NaN,IMG_20250821_074756 (1).jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-21
179,Atestado Médico,MOISES DA SILVA SOUZA,RECH AGRICOLA,GOIANIA LA,702.821.781-71,2025-08-20,1.0,true,NaN,d273606a-9064-4d6b-949f-d0f46dabff2a.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-21

In [ ]:
df = pd.read_excel('data/leroy/ATESTADOS_LEROY_02-09-2025--teste.xlsx')

formated_df = formated_df[formated_df['data_inicio'] > pd.Timestamp('18/08/2025')]

df

,cids,cids_descricao,cpf,data_inicio,data_retorno,hora_fim,hora_inicio,nome_funcionario,matricula,dias_afastamento,data_lancamento,estado_prestador,identificador_prestador,local,nome_prestador,tipo,codigo_tipo,tipo_prestador
0,S932,Ruptura de ligamentos ao nível do tornozelo e ...,39519428860,2025-08-19,NaT,00:00,00:00,NATHALIA CRISTINA THOME,50033499,NaN,03/09/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,9226174652,2025-08-19,2025-08-19,00:00,00:00,MARCIA LAENE SOUSA FERREIRA,50027069,NaN,03/09/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,43354482877,2025-08-19,2025-08-26,00:00,00:00,RONI MOREIRA DOS SANTOS,50032674,NaN,03/09/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,G43,Enxaqueca,35612332874,2025-08-19,2025-08-19,00:00,00:00,JEANE APARECIDA DA SILVA,50036648,NaN,03/09/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,G43,Enxaqueca,3504393114,2025-08-19,2025-08-19,00:00,00:00,DEISY ANNE BORGES LIMA,50036700,NaN,03/09/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,NaN,NaN,60069419027,2025-08-30,2025-08-31,00:00,00:00,INGRID TALASCA DA SILVA,50032906,NaN,03/09/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
674,R11,Náusea e vômitos,42508432890,2025-08-30,2025-08-30,00:00,00:00,HERICK ALVES MAASS,50033143,NaN,03/09/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
675,NaN,NaN,52304913881,2025-08-30,2025-08-30,00:00,00:00,PABLO DE OLIVEIRA SOUZA,50036107,NaN,03/09/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
676,G43,Enxaqueca,3504393114,2025-08-30,2025-08-30,00:00,00:00,DEISY ANNE BORGES LIMA,50036700,NaN,03/09/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
677,M250,Hemartrose,54108242882,2025-08-30,2025-08-30,00:00,00:00,Wendel Neri de Jesus,50037005,NaN,03/09/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
CURR_DIR = os.getcwd()
DATA_DIR = os.path.join(CURR_DIR, 'data')

# Insira o nome da empresa abaixo em minusculo; ex: greif, rech, leroy etc
CLIENT_NAME = 'greif'

FILE_DIR = os.path.join(DATA_DIR, CLIENT_NAME)

In [9]:
pd.set_option('display.max_columns', None)
df = pd.read_csv(f'{FILE_DIR}/chamados_suporte_enduser_retorno_new.csv', delimiter=';')
# df = pd.read_excel('data/default/prototipo.xlsx')
df

,"<img src=""../_lib/img/grp__NM__ico__NM__statusOK.png"" alt="""" width="""" height="""">",Pendente,5 dias úteis,20.289,JONAS PINHEIRO DOS SANTOS,141297,28/08/2025 11:37:28,Unnamed: 7,Greif SP,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,Unnamed: 13,Expert.1
0,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.284,ALAN GOES DOS SANTOS,303243,28/08/2025 09:45:55,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
1,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.281,WEMERSON SANTOS BRITO,1400471,28/08/2025 08:42:07,NaN,GREIF LONDRINA,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
2,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.279,VIVIANE RIBEIRO DE MELO,303247,27/08/2025 18:30:58,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
3,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.274,LUCINEIA MARIA DE JESUS SOUZA,2105782,27/08/2025 13:08:09,28/08/2025 09:05:00,GREIF PARANA/ARAUCARIA,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
4,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.273,LAZARO BRAZ RODRIGUES,140398,27/08/2025 12:42:43,NaN,Greif SP,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
5,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.272,SEVERINO DE FONTE RANGEL,141076,27/08/2025 11:57:46,NaN,Greif SP,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
6,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.270,SEVERINO DE FONTE RANGEL,141076,27/08/2025 11:48:12,NaN,Greif SP,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
7,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.267,JACKSON GOES DA SILVA,303227,27/08/2025 07:31:24,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
8,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.265,DAVI DOS SANTOS MAGALHAES,303216,26/08/2025 17:42:30,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
9,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.264,JOAO MAICON NUNES DE JESUS,303284,26/08/2025 16:36:36,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
10,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.260,JACKSON GOES DA SILVA,303227,26/08/2025 14:17:49,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
11,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.259,JACKSON GOES DA SILVA,303227,26/08/2025 14:13:16,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
12,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.258,JACKSON GOES DA SILVA,303227,26/08/2025 14:11:04,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
13,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.256,JACKSON GOES DA SILVA,303227,26/08/2025 12:42:42,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
14,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.255,JACKSON GOES DA SILVA,303227,26/08/2025 12:32:07,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
15,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.254,JACKSON GOES DA SILVA,303227,26/08/2025 12:25:25,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
16,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.253,JACKSON GOES DA SILVA,303227,26/08/2025 12:20:36,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
17,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.247,JOHN OLIVEIRA MARQUES DA SILVA,141480,26/08/2025 02:22:23,NaN,Greif SP,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
18,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.246,JOAO RODRIGO SANTANA DOS SANTOS,303262,25/08/2025 19:46:50,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
19,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.245,ALEXANDRE PEREIRA GONZALEZ,207791,25/08/2025 19:37:51,NaN,Greif RJ,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
20,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.240,LUCAS EDUARDO VENZO COELHO,602551,25/08/2025 12:36:48,NaN,GREIF ESTEIO,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
21,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.232,YAGO AGUIAR DE LIMA,289784,24/08/2025 23:56:10,NaN,GREIF MANAUS,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
22,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.231,ISRAEL COLARES DE SOUZA,290495,24/08/2025 18:58:19,NaN,GREIF MANAUS,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
23,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.225,SANDRA COSTA DOS SANTOS,303275,23/08/2025 05:22:34,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
24,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.224,IZAEL SILVA LIRA,113380,22/08/2025 21:53:22,NaN,GREIF MANAUS,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
25,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.221,ANDERSON DA SILVA SOUZA,208006,22/08/2025 16:29:58,NaN,Greif RJ,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
26,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.220,KARINE TAVARES FARIAS COSTA,141177,22/08/2025 15:52:32,NaN,Greif SP,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
27,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.218,DANIEL OLIVEIRA NEPOMUCENO,303244,22/08/2025 15:05:55,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
28,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.216,JOSE CARLOS DE SOUZA,303123,22/08/2025 14:19:38,NaN,GREIF ARATU,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
29,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.208,ALEXANDRE PEREIRA GONZALEZ,207791,21/08/2025 20:03:01,NaN,Greif RJ,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
30,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.202,ARMEZINA MARIA DO NASCIMENTO,141036,21/08/2025 13:16:44,NaN,Greif SP,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
31,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.201,ARMEZINA MARIA DO NASCIMENTO,141036,21/08/2025 13:14:30,NaN,Greif SP,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
32,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.193,YAN LUIZ SILVA REIS,208018,20/08/2025 19:41:39,NaN,Greif RJ,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
33,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.182,FERNANDA DA SILVA ANDRADE,1400454,20/08/2025 11:41:37,NaN,GREIF LONDRINA,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
34,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Pendente,5 dias úteis,20.178,ISRAEL COLARES DE SOUZA,290495,20/08/2025 07:05:22,NaN,GREIF MANAUS,Expert,Atestado médico,Envio de Atestado Médico,Atestado Médico,NaN,Expert
35,"<img src=""../_lib/img/grp__NM__ico__NM__status...",Responsável Redirecionado,5 dias úteis,20.190,LUCIANO LEANDRO SILVA,140927,20/08/2025 18:25:27,21/08/2025 12:51:00,Greif SP,Karine Costa,Outros,Outros - detalhe sua necessidade,"Declaração de presença,precisei fazer exames d...",21/08/2025 12:51:00,Expert

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 22 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Unnamed: 0                                                                  164 non-null    int64
 1    Tipo de justificativa                                                      153 non-null    object
 2   Colaborador                                                                 164 non-null    object
 3   Cadastro                                                                    28 non-null     object
 4   Empresa                                                                     153 non-null    object
 5   Filial                                                                      153 non-null    object
 6   CPF                                                                         147 non-null    object
 7   Data Inicial do afastamento                                                 163 non-null    object
 8   Quantidade de Dias de Afastamento                                           153 non-null    object
 9   Estou ciente que só devo retornar ao trabalho ao fim dos dias de atestado.  153 non-null    object
 10  Observações                                                                 103 non-null    object
 11  Justificativa                                                               146 non-null    object
 12  Justificativa Validada                                                      148 non-null    object
 13  E-mail Pessoal                                                              5 non-null      object
 14  Telefone Pessoal                                                            5 non-null      object
 15  Formulário                                                                  5 non-null      object
 16  Certidão de Nascimento                                                      5 non-null      object
 17  Ciente do Gestor                                                            2 non-null      object
 18  Grau de Parentesco                                                          1 non-null      object
 19  Data do Abono                                                               1 non-null      object
 20  Autorização do Gestor                                                       1 non-null      object
 21   Empresa                                                                    11 non-null     object
dtypes: int64(1), object(21)
memory usage: 28.3+ KB